### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Rickyzie**
discord name = 黃柏翔
http://54.184.133.13:3000/attraction/58
http://54.184.133.13:3000/
再麻煩老師了～～

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Slider should extend to full width and keep no margin space with navigator bar.

**Comment by Rickyzie** [comment]
fixed slider layout

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Comment by Rickyzie** [comment]
got it !I had re-requested

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
